server:
  port: 8088

spring:
  application:
    name: report-service

  jpa:
    show-sql: true

  main:
    allow-bean-definition-overriding: true

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

  jackson:
    serialization:
      INDENT_OUTPUT: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka