server:
  port: 8088

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: "4d9f23ddae91bfb780a12de9e1abcf849e51763ff015cabf4e4f61dfcc177f3ba0f5d7b4f6b52d4b18956773fdd10498f0e4b923bcf758e2c4c15b735dc9519f"
  expiration-time: 3600
