spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true

jwt:
  secret: testsecretforsigningjwtinmemory
  expirationTime: 360000

logging:
  level:
    root: ERROR
    org:
      springframework: ERROR
      hibernate: ERROR
server:
  error:
    whitelabel:
      enabled: false
    include-message: always
