spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_manager
    username: root
    password: Andy!1202
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  web:
    cors:
      allowed-origin-patterns: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

jwt:
  secret: asilu3rnkuBHKUHBadasdaASKUFBWERIU3Q4B12321312YTGIUTGBQYEKRUQHBRWKJRTBHR23U4KYBWJKBjhdsbfsasilu3rnkuBHKUHBadasdaASKUFBWERIU3Q4B12321312YTGIUTGBQYEKRUQHBRWKJRTBHR23U4KYBWJKBjhdsbfs...
  expirationTime: 360000

logging:
  level:
    root: ERROR
    org:
      springframework: ERROR
      hibernate: ERROR
      springframework.security: DEBUG
      springframework.security.web.FilterChainProxy: DEBUG
    com:
      andy:
        proiect_facultate: ERROR
